#!/bin/bash
# =============================================================
# build.sh — Build the MMM-WEALTH model (headless/NW mode)
# =============================================================
# Automatically detects macOS or Linux, checks prerequisites,
# generates system options, and compiles the lsdNW executable.
#
# Usage:
#   ./build.sh          Build the model
#   ./build.sh clean    Remove compiled files
# =============================================================

set -e

MODE="${1:-build}"
DST="$(cd "$(dirname "$0")" && pwd)"
cd "$DST"

# --- Detect platform ---
OS="$(uname -s)"
case "$OS" in
    Darwin) PLATFORM="macOS" ;;
    Linux)  PLATFORM="Linux" ;;
    *)
        echo "Error: Unsupported platform '$OS'."
        echo "This build script supports macOS and Linux."
        echo "On Windows, use WSL (Windows Subsystem for Linux)."
        exit 1
        ;;
esac

# --- Clean mode ---
if [ "$MODE" = "clean" ]; then
    echo "Cleaning compiled files..."
    rm -f src/*.o *.o lsdNW lsdNW.exe system_options.txt
    echo "Done."
    exit 0
fi

echo "=============================================="
echo "  MMM-WEALTH Model — Headless Build"
echo "  Platform: $PLATFORM"
echo "=============================================="
echo ""

# --- Check prerequisites ---
MISSING=0

if ! command -v g++ &>/dev/null; then
    echo "Error: g++ not found."
    if [ "$PLATFORM" = "macOS" ]; then
        echo "  Install with: xcode-select --install"
    else
        echo "  Install with: sudo apt install build-essential   (Ubuntu/Debian)"
        echo "            or: sudo dnf install gcc-c++ make      (Fedora/RHEL)"
    fi
    MISSING=1
fi

if ! command -v make &>/dev/null; then
    echo "Error: make not found."
    if [ "$PLATFORM" = "macOS" ]; then
        echo "  Install with: xcode-select --install"
    else
        echo "  Install with: sudo apt install build-essential   (Ubuntu/Debian)"
        echo "            or: sudo dnf install make              (Fedora/RHEL)"
    fi
    MISSING=1
fi

# Check for zlib
ZLIB_OK=0
if [ "$PLATFORM" = "macOS" ]; then
    # macOS: zlib ships with Xcode command line tools
    if [ -f /usr/include/zlib.h ] || xcrun --show-sdk-path &>/dev/null; then
        ZLIB_OK=1
    fi
else
    # Linux: check for zlib-dev header
    if [ -f /usr/include/zlib.h ] || [ -f /usr/include/x86_64-linux-gnu/zlib.h ]; then
        ZLIB_OK=1
    fi
fi

if [ "$ZLIB_OK" -eq 0 ]; then
    echo "Warning: zlib headers may not be installed."
    if [ "$PLATFORM" = "macOS" ]; then
        echo "  Install with: xcode-select --install"
    else
        echo "  Install with: sudo apt install zlib1g-dev    (Ubuntu/Debian)"
        echo "            or: sudo dnf install zlib-devel    (Fedora/RHEL)"
    fi
    echo "  (Continuing anyway — build will fail if zlib is truly missing.)"
    echo ""
fi

if [ "$MISSING" -eq 1 ]; then
    echo ""
    echo "Please install the missing prerequisites and try again."
    exit 1
fi

echo "Prerequisites: OK"
echo ""

# --- Generate system_options.txt ---
echo "Generating system_options.txt for $PLATFORM..."

cat > system_options.txt << 'EOF'
# Auto-generated by build.sh — do not commit
SRC=src

# Library options
PATH_HEADER=.
PATH_LIB=.
LIB=-lz -lpthread

# Compiler options
CC=g++
GLOBAL_CC=-std=c++14 -w
SSWITCH_CC=-fnon-call-exceptions -O3
EOF

echo "Done."
echo ""

# --- Combine makefiles and build ---
echo "Compiling lsdNW..."
echo ""

COMBINED_MK="$(mktemp)"
cat model_options.txt system_options.txt makefile-NW > "$COMBINED_MK"

NCPU=1
if [ "$PLATFORM" = "macOS" ]; then
    NCPU=$(sysctl -n hw.ncpu 2>/dev/null || echo 1)
else
    NCPU=$(nproc 2>/dev/null || echo 1)
fi

make -f "$COMBINED_MK" -j"$NCPU"
rm -f "$COMBINED_MK"

echo ""
echo "=============================================="
echo "  Build successful!"
echo "  Executable: ./lsdNW ($(du -h lsdNW | cut -f1 | xargs))"
echo "=============================================="
echo ""
echo "Quick start:"
echo "  ./lsdNW -f Scenario_0.lsd -s 1 -e 50 -o Results_Scenario_0 -b"
echo ""
echo "Run all 4 scenarios in parallel:"
echo "  ./run_all.sh"
echo ""
